[theme]
# Primary color (used for interactive elements)
primaryColor = "#7C3AED"

# Background color of the app
backgroundColor = "#F5F3FF"

# Secondary background color (used for st.sidebar, st.info, st.warning, st.success, st.error)
secondaryBackgroundColor = "#EDE9FE"

# Text color
textColor = "#1E1B4B"

# Font
font = "sans serif"

[client]
# Controls the default scroll behavior on st.write()
showErrorDetails = true

[logger]
# Log level
level = "info"

[server]
# Port on which the server will listen
port = 8501

# Whether to enable CORS headers when the app is deployed on the same domain
enableCORS = true

# Whether to enable running the app in headless mode
headless = true
